### ISSUE TITLE
Milestone 0

### ISSUE THREAD

**Issue by devdiva** [devdiva/cnyttan#1]
* [ ] Initial design and specifications
* [ ] Initial visual language and design direction
* [ ] Initial toolchain setup
